
import React, { useEffect } from "react";

interface Course {
  title: string;
  image: string;
}

interface CourseData {
  [ageGroup: string]: Course[];
}

interface AgeCoursesProps {
  activeAge: string;
  coursesData: CourseData;
  onAgeChange: (age: string) => void;
  language: "en" | "ar";
  translations: {
    coursesByAge: string;
  };
}

const AgeCoursesSection: React.FC<AgeCoursesProps> = ({ 
  activeAge, 
  coursesData, 
  onAgeChange, 
  language, 
  translations
}) => {
  useEffect(() => {
    renderCourses(activeAge);
  }, [activeAge, language]);
  
  const renderCourses = (ageGroup: string) => {
    const courseListContainer = document.getElementById('course-list');
    if (!courseListContainer || !coursesData[ageGroup]) return;
    
    const coursesHTML = `
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        ${coursesData[ageGroup].map(course => `
          <div class="course-card bg-white rounded-lg shadow-lg overflow-hidden">
            <div class="aspect-video w-full overflow-hidden">
              <img 
                src="${course.image}" 
                alt="${course.title}" 
                class="w-full h-full object-cover"
              />
            </div>
            <div class="p-4">
              <h3 class="text-xl font-semibold">${course.title}</h3>
            </div>
          </div>
        `).join('')}
      </div>
    `;
    
    courseListContainer.innerHTML = coursesHTML;
  };

  return (
    <section className="content" id="Ages">
      <h2 className="text-4xl font-bold text-center text-purple-900 mb-8">{translations.coursesByAge}</h2>
      
      <div className="button-container grid grid-cols-2 md:grid-cols-5 gap-1">
        {Object.keys(coursesData).map(age => (
          <button 
            key={age}
            className={`button ${activeAge === age ? 'active' : ''}`} 
            data-group={age}
            onClick={() => onAgeChange(age)}
          >
            {language === 'en' ? `Age ${age}` : `العمر ${age}`}
          </button>
        ))}
      </div>

      <div className="courses" id="course-list">
        {/* Content dynamically generated by renderCourses */}
      </div>
    </section>
  );
};

export default AgeCoursesSection;
