// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fofwiiaunvixzjfxiqak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZndpaWF1bnZpeHpqZnhpcWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NzMxNTgsImV4cCI6MjA2MzQ0OTE1OH0.RcBLjltBYJE3EJiievN1kiQIcBHTGM6gsRocDATR3Jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);